# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install scikit-learn
  - pip install coverage
  - pip install coveralls
  - pip install .

script:
  - pytest

after_success:
  - coverage report -m
  - coveralls
