# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License

language: python

python:
  - "3.6"

install:
  - pip install numpy
  - pip install scipy
  - pip install pandas
  - pip install scikit-learn
  - pip install tensorflow
  - pip install keras
  - pip install pytest
  - pip install pytest-cov
  - pip install codecov
  - pip install .

script:
  - pytest --cov=hyperactive/

after_success:
  - codecov
