# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

install:
  - pip install .

script:
  - nosetests --with-coverage --cover-package=hyperactive

after_success:
  - coverage report -m
  - coveralls
