# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License
os:
  - linux

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip hypermemory
  - pip derivative-free-optimizers
  - pip install packaging
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
  - pip install .

script:
  - pytest --cov=hyperactive/ -p no:warnings

after_success:
  - coveralls
