# Author: Simon Blanke
# Email: simon.blanke@yahoo.com
# License: MIT License

language: python

python:
  - "3.6"
  - "3.5"
  - "3.4"

install:
  - pip install numpy
  - pip install scikit-learn
  - pip install tqdm
  - pip install keras
  - pip install meta-learn
script:
  - pytest
